(function () {
  const SimpleContainer = Java.loadClass('net.minecraft.world.SimpleContainer');
  const ItemStack = Java.loadClass('net.minecraft.world.item.ItemStack');
  const SoundEvents = Java.loadClass('net.minecraft.sounds.SoundEvents');
  const SoundSource = Java.loadClass('net.minecraft.sounds.SoundSource');

  // Wrap a chest in planks with a slab on top
  ServerEvents.recipes(event => {
    event.shaped('cowpewter_bap:shipping_bin', [
      'PSP',
      'PCP',
      'PPP'
    ], {
      P: '#minecraft:planks',
      C: 'minecraft:chest',
      S: '#minecraft:wooden_slabs'
    });
  });

  const STANDARD_STACK_SIZE = 64;
  const SMALL_STACK_SIZE = 16;

  const BIN_SLOTS = 27;

  const OPEN_BINS = {};

  const COIN_VALUES = [
    { value: 500, id: 'cowpewter_bap:coin_500' },
    { value: 100, id: 'cowpewter_bap:coin_100' },
    { value: 10, id: 'cowpewter_bap:coin_10' },
    { value: 1, id: 'cowpewter_bap:coin_1' },
  ];

  const totalToCoins = (total) => {
    const coins = [];
    let remaining = total;

    COIN_VALUES.forEach(rung => {
      let numCoins = Math.floor(remaining / rung.value);
      remaining -= numCoins * rung.value;
      while (numCoins > 0) {
        let chunk = Math.min(numCoins, STANDARD_STACK_SIZE);
        coins.push(Item.of(rung.id, chunk));
        numCoins -= chunk;
      }
    });

    return coins;
  };

  const makeBuckets = (count) => {
    let bucketStacks = [];
    let remaining = count;

    while (remaining > 0) {
      let chunk = Math.min(remaining, SMALL_STACK_SIZE);
      bucketStacks.push(Item.of('minecraft:bucket', chunk));
      remaining -= chunk;
    }

    return bucketStacks;
  };

  PlayerEvents.inventoryClosed('kubejs:menu', event => {
    if (!event.player) return;
    const bin = OPEN_BINS[event.player.uuid];
    if (!bin) return;

    const numSlots = bin.getContainerSize();
    const shipped = {};
    let bucketsToReturn = 0;
    let total = 0;
    for (let i = 0; i < numSlots; i++) {
      let stack = bin.getItem(i);
      let price = priceOf(stack);
      if (price > 0) shipped[String(stack.id)] = true;
      total += price * stack.count;

      if (String(stack.id) === 'minecraft:milk_bucket') {
        bucketsToReturn += stack.count; // should always be 1 but you never know
      }
    }
    if (total === 0) {
      // Nothing to sell, Cleanup
      delete OPEN_BINS[event.player.uuid];
      return;
    }

    // If we sold Milk Buckets, return the empties
    if (bucketsToReturn > 0) {
      let buckets = makeBuckets(bucketsToReturn);
      buckets.forEach(b => {
        event.player.give(b);
      });
    }

    // Deliver the money
    let toAdd = totalToCoins(total);
    let pouch = BAP_POUCH.getPouchSlotStack(event.player);
    if (!pouch.stack) {
      // just give to player directly if pouch lookup fails
      toAdd.forEach(item => {
        event.player.give(item);
      });
    } else {
      let container = BAP_POUCH.getLinkedContainerFromPouch(event.player, pouch.stack);
      // precondense to maximize room
      BAP_POUCH.condenseContainer(container);
      toAdd.forEach(item => {
        let remainder = container.addItem(item);
        if (remainder.count) {
          event.player.give(remainder);
        }
      });
      // post condense for cleanup
      BAP_POUCH.condenseContainer(container);
    }
    // Now that all items are wherever they will land...
    event.player.sendInventoryUpdate();

    // Completionism: tick one objective per distinct item actually sold.
    grantShipAdvancements(event.player, shipped);
    // Market chapter: the "sell your first item" objective. Hand-written, so it
    // lives under advancement/quest/ -- generate_ship_quests.py wipes
    // advancement/ship/ on every run.
    grantAdvancement(event.player, FIRST_SALE_ADVANCEMENT);

    // Notify player of sale
    event.player.setStatusMessage(Text.of('Sold for $' + total));
    event.player.playNotifySound(SoundEvents.EXPERIENCE_ORB_PICKUP, SoundSource.PLAYERS, 0.8, 1.2);

    // Cleanup
    delete OPEN_BINS[event.player.uuid];
  });

  PlayerEvents.loggedIn(event => {
    const player = event.player;
    if (!player) return;
    // Cleanup in case player disco'd
    delete OPEN_BINS[player.uuid];
  });

  PlayerEvents.loggedOut(event => {
    const player = event.player;
    if (!player) return;
    // Cleanup in case player disco'd
    delete OPEN_BINS[player.uuid];
  });

  // Each shippable item has an invisible advancement (generated by
  // tools/generate_ship_quests.py) watched by one Completionism objective.
  // Re-granting one a player already holds is a vanilla no-op, so shipping the
  // same item twice needs no guard. Runs on the server command source, which is
  // permission 4; the player's own source is their op level and would fail.
  const FIRST_SALE_ADVANCEMENT = 'cowpewter_bap:quest/first_sale';

  const grantAdvancement = (player, adv) => {
    player.server.runCommandSilent(
      'advancement grant ' + player.username + ' only ' + adv
    );
  };

  const grantShipAdvancements = (player, shipped) => {
    let id;
    for (id in shipped) {
      let adv = global.BAP_SHIP_ADVANCEMENTS[id];
      if (!adv) continue;
      grantAdvancement(player, adv);
    }
  };

  // Simple because every sellable item must have a price. No price, no sale, no tags!
  const priceOf = (stack) => {
    return (stack && !stack.isEmpty() && global.BAP_PRICES[String(stack.id)]) || 0;
  };

  const openBin = (player) => {
    if (!player) return;

    // Need to create an array of BIN_SLOTS ItemStack.EMPTY
    // As subclassing SimpleContainer means we can't use the int constructor
    const tempArr = [];
    for (let i = 0; i < BIN_SLOTS; i++) {
      tempArr.push(ItemStack.EMPTY);
    }

    const tempInv = new JavaAdapter(
      SimpleContainer,
      { canPlaceItem: (_, stack) => priceOf(stack) > 0 },
      tempArr
    );
    OPEN_BINS[player.uuid] = tempInv;
    player.openInventoryGUI(tempInv, Text.of('Shipping Bin'));
  };

  BlockEvents.rightClicked('cowpewter_bap:shipping_bin', event => {
    const player = event.player;
    if (!player) return;

    // rightClicked fires once per hand. Opening twice replaces the first menu,
    // and that displacement fires inventoryClosed against the new empty
    // container -- which takes the total === 0 branch and deletes the
    // OPEN_BINS entry the real close needs. Cancel still runs for both hands
    // so nothing gets placed on the bin.
    if (String(event.hand) === 'MAIN_HAND') {
      openBin(player);
    }
    event.cancel();
  });
})();
