#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 14 06:03:56 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9.1.zip
